services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_ai_app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
    depends_on:
      mysql-test:
        condition: service_started
    networks:
      - laravel-net

  mysql-test:
    image: mysql:8.0
    container_name: mysql8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: laravel
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-net

  # ollama:
  #   image: ollama/ollama
  #   container_name: ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   networks:
  #     - laravel-net

volumes:
  db_data:
  # ollama_data:

networks:
  laravel-net:
    driver: bridge